server:
  port: 10000
  debug: false

signal:
  number: "+SENDER_NUMBER"    # replace with your registered Signal number
  recipients:
    - "group.XXXXXXXXXXX=="   # replace with your Signal group ID
  send: "http://signal-cli-rest-api:8080/v2/send"

alertmanager:
  generatorURL: false
  ignoreLabels:
    - "__replica__"
